from fast_openai import run_openai_str, RequestArgs, run_openai_embed, run_auto_str
from fast_openai.base import Result
import logging
logger = logging.getLogger(__name__)

import numpy as np
from typing import Literal
import re


def extract_answers(xml_fragment: str) -> list[str]:
    contents = re.findall(r"<answer>(.*?)</answer>", xml_fragment, re.DOTALL)
    return [
        c.strip()
        for c in contents
    ]

def category_to_string(
        cat_data: dict[str, str],
        mode: Literal['headings', 'concat'] = 'headings'
    ) -> str:
    
    if mode == 'headings':
        return f'Task: {cat_data["task"]}\nOccupation: {cat_data["occupation"]}'
    
    elif mode == 'concat':
        return f'{cat_data["task"]}\n{cat_data["occupation"]}'
    
    raise ValueError(f'invalid mode: {mode}')

def embed_model_conditional_ensemble(
        cat_data_batch: list[dict[str, str]],
        task_prompt: str,
        convo_prompt: str,
        n_trials: int,
        task_model_name: str = 'openai/gpt-4.1',
        convo_model_name: str = 'openai/gpt-4.1-mini',
        task_temperature: float = 1.0,
        convo_temperature: float = 1.0
    ) -> list[np.ndarray]:
    """Embeds a list of categories by first generating examples for category, then ensembling across the embeds for the generated examples.

    Examples are generated by first using a more powerful model to propose user request topics & then using a cheaper model to generate the actual conversations.

    Args:
        cat_data_batch (list[dict[str, str]]): a list of categories to embed; each dict has keys task & occupation corresponding to the O*NET task and occupation.
        task_prompt (str): prompt used to generate user request topics
        convo_prompt (str): prompt used to generate conversations conditioned on user requests
        n_trials (int): number of conversations to generate per category (averages over embeddings for all of the ``n_trials`` conversations generated)
        task_model_name (str): model used to propose user request topics. Default to ``openai/gpt-4.1``
        convo_model_name (str): model used to generate conversations conditioned on task topics. Default to ``openai/gpt-4.1-mini``
        task_temperature (float): temperature used to propose user request topics. Default to ``1.0``
        convo_temperature (float): temperature used to generate conversations conditioned on task topics. Default to ``1.0``
    """

    task_model_inputs = [
        task_prompt.format(
            category=category_to_string(cat_data),
            n_trials=n_trials
        )
        for cat_data in cat_data_batch
    ]

    logger.info(f"embed_model_conditional_ensemble sample input:\n{task_model_inputs[0]}")

    task_model_outputs = run_auto_str(
        task_model_inputs,
        full_model_name=task_model_name,
        temperature=task_temperature,
        num_workers=64,
        max_tokens = 8192,
        validation_function=lambda y: len(extract_answers(y)) == n_trials,
        request_args=RequestArgs(
            hash_keys=True,
            num_retries=4
        )
    )
    task_descrips_all = [
        # assume x.output not None
        extract_answers(x.output) # type: ignore
        for x in task_model_outputs
    ]

    # make sure we generated the correct num examples
    for examples in task_descrips_all:
        assert len(examples) == n_trials

    '''
    n*m examples -> n*m convos
    '''
    convo_model_inputs = [
        [
            convo_prompt.format(task=t)
            for t in task_descrips_single
        ]
        for task_descrips_single in task_descrips_all
    ]

    # flatten
    lengths = [len(sublist) for sublist in convo_model_inputs]
    convo_model_inputs_flat = [
        item
        for sublist in convo_model_inputs
        for item in sublist
    ]
    
    # run on flat list
    convo_res_flat = run_auto_str(
        convo_model_inputs_flat,
        full_model_name=convo_model_name,
        temperature=convo_temperature,
        num_workers=128,
        max_tokens = 8192,
        request_args=RequestArgs(
            hash_keys=True,
            post_timeout=5 * 60,
            total_timeout=5 * 60,
            num_retries=4
        )
    )

    convo_outputs_flat: list[str] = []
    for x in convo_res_flat:
        assert x.output is not None
        convo_outputs_flat.append(x.output)

    '''
    n*m convos -> n*m embeds
    '''
    embeds_res_flat = run_openai_embed(
        convo_outputs_flat,
        model_name='text-embedding-3-small',
        num_workers=64,
        request_args=RequestArgs(
            hash_keys=True,
        )
    )
    embeds_flat: list[list[float]] = []
    for x in embeds_res_flat:
        assert x.output is not None
        embeds_flat.append(x.output)

    '''
    n*m embeds -> n avg'd embeds, averaging across each of m embeds
    '''
    convo_avg_embeds: list[np.ndarray] = []
    idx = 0
    for length in lengths:
        # take the next `length` items from the flat result
        chunk_vec = np.array(embeds_flat[idx : idx + length])
        assert len(chunk_vec.shape) == 2 and chunk_vec.shape[0] == n_trials
        convo_avg_embeds.append(chunk_vec.mean(axis=0))
        idx += length

    return convo_avg_embeds

def embed_concat(
        cat_data_batch: list[dict[str, str]],
    ) -> np.ndarray:
    """Embeds a list of task statements and occupations, concatenating the two.

    Args:
        cat_data_batch (list[dict[str, str]]): a list of categories to embed; each dict has keys task & occupation corresponding to the O*NET task and occupation.
    
    Returns:
        np.ndarray: embedding for each input category
    """

    embed_inp = [
        category_to_string(cat_data, mode='concat')
        for cat_data in cat_data_batch
    ]
    logger.info(len(embed_inp))

    embeds = run_openai_embed(
        embed_inp,
        model_name='text-embedding-3-small',
        num_workers=16
    )

    for x in embeds:
        assert x.output is not None

    return np.array([x.output for x in embeds])

def embed_direct(
        inp_strs: list[str]
    ) -> np.ndarray:
    """Embeds a list of strings.

    Args:
        inp_strs (list[str]): a list of strings to embed
    
    Returns:
        np.ndarray: embedding for each input string
    """

    logger.info(len(inp_strs))

    embeds = run_openai_embed(
        inp_strs,
        model_name='text-embedding-3-small',
        num_workers=16
    )

    for x in embeds:
        assert x.output is not None

    return np.array([x.output for x in embeds])
